// Generated by scripts/publish-fstory-homepages.mjs — do not edit by hand.
// Source of truth: scripts/fstory-lineage.mjs

export type FstoryEditionId = 'L0' | 'L1' | 'L2.0' | 'L2.1' | 'L2.2' | 'L3';

export type FstoryCaptureId = '20010715123146' | '20010723051951' | '20010925220320' | '20011202212712' | '20020325014505' | '20020924164928' | '20021120053627' | '20021128181318' | '20030726202839';

export type FstoryCapture = {
    timestamp: FstoryCaptureId;
    date: string;
};

// One entry per design generation. Every capture that belongs to a generation is
// merged into it, so these are editions of the site, not crawler visits.
export type FstoryEdition = {
    id: FstoryEditionId;
    label: string;
    period: string;
    summary: string;
    directory: FstoryCaptureId;
    date: string;
    builtFrom: FstoryCapture[];
};

export const FSTORY_EDITIONS: FstoryEdition[] = [
    {
        "id": "L0",
        "label": "도메인 호스팅 안내",
        "period": "2001-07-15",
        "summary": "도메인 등록 대행사의 기본 안내 화면. 홈페이지 본체가 아니다.",
        "directory": "20010715123146",
        "date": "2001-07-15",
        "builtFrom": [
            {
                "timestamp": "20010715123146",
                "date": "2001-07-15"
            }
        ]
    },
    {
        "id": "L1",
        "label": "클래식 (1998 ~ 2001-07)",
        "period": "1998 ~ 2001-07-23",
        "summary": "프레임 없이 title1~4.gif 메뉴 그림을 세로로 늘어놓은 초기 계보. Wayback에 남은 마지막 상태가 2001-07-23이다.",
        "directory": "20010723051951",
        "date": "2001-07-23",
        "builtFrom": [
            {
                "timestamp": "20010723051951",
                "date": "2001-07-23"
            }
        ]
    },
    {
        "id": "L2.0",
        "label": "ver 2.0 최초판",
        "period": "2001-09 ~ 2002-03",
        "summary": "index.html 안의 800x600 iframe이 main.html(42/560 2분할 프레임)을 부른다. 메뉴에 ai·study 항목이 있다.",
        "directory": "20011202212712",
        "date": "2001-12-02",
        "builtFrom": [
            {
                "timestamp": "20010925220320",
                "date": "2001-09-25"
            },
            {
                "timestamp": "20011202212712",
                "date": "2001-12-02"
            }
        ]
    },
    {
        "id": "L2.1",
        "label": "ver 2.0 메뉴 개편판",
        "period": "2002-03 ~ 2002-11-20",
        "summary": "프레임 구조는 그대로이고 메뉴가 teatime·tech·zboard 중심으로 바뀐다. 본문 첫 화면이 diary/diary.html이다.",
        "directory": "20021120053627",
        "date": "2002-11-20",
        "builtFrom": [
            {
                "timestamp": "20020325014505",
                "date": "2002-03-25"
            },
            {
                "timestamp": "20020924164928",
                "date": "2002-09-24"
            },
            {
                "timestamp": "20021120053627",
                "date": "2002-11-20"
            }
        ]
    },
    {
        "id": "L2.2",
        "label": "ver 2.0 5분할 재설계판",
        "period": "2002-11-28 ~ 2003-07",
        "summary": "main.html이 topmenu·left·content·right·bottom 5분할 프레임으로 바뀌고 bgm 프레임이 붙는다. album·cartoon·media·insidece 메뉴가 새로 생기고 싸이월드 링크가 처음 등장한다.",
        "directory": "20021128181318",
        "date": "2002-11-28",
        "builtFrom": [
            {
                "timestamp": "20021128181318",
                "date": "2002-11-28"
            }
        ]
    },
    {
        "id": "L3",
        "label": "ver 3.0 싸이월드 연동판",
        "period": "2003-07-26",
        "summary": "프레임을 모두 걷어내고 단일 index.html로 돌아간 마지막 판. 본문 대부분을 싸이월드 미니홈피에 넘겼다.",
        "directory": "20030726202839",
        "date": "2003-07-26",
        "builtFrom": [
            {
                "timestamp": "20030726202839",
                "date": "2003-07-26"
            }
        ]
    }
];

export type FstoryAnnex = {
    id: string;
    label: string;
    period: string;
    snapshot: FstoryCaptureId;
    entry: string;
    summary: string;
};

// Earlier addresses the later editions never link back to. Offered as their own
// restore points so the recovered pages are reachable.
export const FSTORY_ANNEXES: FstoryAnnex[] = [
    {
        "id": "netian",
        "label": "네티앙 시절",
        "period": "1999-03 ~ 2001",
        "snapshot": "20011202212712",
        "entry": "netian/index__e97a8fd3.html",
        "summary": "fstory.net 도메인을 쓰기 전, my.netian.com/~fstory 에 있던 홈페이지. 첫 화면에 \"1999.3.17부터 방문자\"와 \"100% 메모장 노가다\" 라고 적혀 있다. L1 클래식 계보와 같은 title1~4.gif 이미지맵 메뉴를 쓴다."
    },
    {
        "id": "chollian-guestbook",
        "label": "천리안 방명록",
        "period": "2001 ~ 2002",
        "snapshot": "20021128181318",
        "entry": "chollian/cgi/pury/purybbs.html",
        "summary": "cgi.chollian.net/~foreststory 에 있던 PURY BBS 방명록. 목록 화면에 글 본문이 그대로 실리는 형식이라 오간 글과 답글이 남아 있다. 캡처마다 다른 쪽이 잡혀서 한 캡처만으로는 일부만 보이므로, 모든 캡처의 글을 번호로 합쳐 한 페이지로 다시 세웠다."
    }
];

export const FSTORY_EDITION_IDS = FSTORY_EDITIONS.map((edition) => edition.id);

export const editionOf = (id: string) => FSTORY_EDITIONS.find((edition) => edition.id === id);
