// Generated by scripts/publish-fstory-homepages.mjs — do not edit by hand.
// Source of truth: scripts/fstory-lineage.mjs

export type FstoryEditionId = 'L0' | 'L1' | 'L2.0' | 'L2.1' | 'L2.2' | 'L3';

export type FstoryCaptureId = '20010715123146' | '20010723051951' | '20010925220320' | '20011202212712' | '20020325014505' | '20020924164928' | '20021120053627' | '20021128181318' | '20030726202839';

export type FstoryCapture = {
    timestamp: FstoryCaptureId;
    date: string;
};

// One entry per design generation. Every capture that belongs to a generation is
// merged into it, so these are editions of the site, not crawler visits.
export type FstoryEdition = {
    id: FstoryEditionId;
    label: string;
    period: string;
    summary: string;
    directory: FstoryCaptureId;
    date: string;
    builtFrom: FstoryCapture[];
};

export const FSTORY_EDITIONS: FstoryEdition[] = [];

// Editions restored from Luke's own kept files rather than from the archive.
// They open the same timeline and belong in the same list.
export type FstoryCuratedEdition = {
    id: string;
    label: string;
    period: string;
    summary: string;
    base: string;
    entry: string;
};

// The ver 2.0 era, published once from every capture that caught it.
export const FSTORY_MERGED_EDITION = {
    "id": "M2",
    "label": "ver 2.0 통합본",
    "period": "2001-09 ~ 2003-07",
    "directory": "ver2-merged",
    "summary": "ver 2.0 시대의 세 캡처를 하나로 합친 편집본. 화면은 2002년 11월 20일 판을 쓰고, 내용은 세 캡처가 가진 것을 모두 담았다. 어느 시점에도 이대로 존재한 적은 없다.",
    "builtFrom": [
        "20011202212712",
        "20021120053627",
        "20021128181318",
        "20030726202839"
    ]
};

export const FSTORY_CURATED_EDITIONS: FstoryCuratedEdition[] = [
    {
        "id": "C1997",
        "label": "1997년 판",
        "period": "1997",
        "summary": "가장 이른 판. 루크가 직접 보관해 온 파일이고, 목록에만 남아 본문을 잃었던 시 27편을 뒷날 판에서 되찾아 채웠다.",
        "base": "/1997-homepage",
        "entry": "index.html"
    },
    {
        "id": "C1998",
        "label": "클래식 (1998 ~ 2001.07)",
        "period": "1998 ~ 2001-07",
        "summary": "title1~4.gif 메뉴 그림을 세로로 늘어놓은 초기 계보. 루크의 보관본을 바탕으로, 2001년 7월 캡처에만 남아 있던 자료를 더해 완성했다.",
        "base": "/1998-homepage",
        "entry": "index.html"
    }
];

export type FstoryAnnex = {
    id: string;
    label: string;
    period: string;
    snapshot: FstoryCaptureId;
    entry: string;
    summary: string;
};

// Earlier addresses the later editions never link back to. Offered as their own
// restore points so the recovered pages are reachable.
export const FSTORY_ANNEXES: FstoryAnnex[] = [
    {
        "id": "netian",
        "label": "네티앙 시절",
        "period": "1999-03 ~ 2001",
        "snapshot": "20011202212712",
        "entry": "netian/index__e97a8fd3.html",
        "summary": "fstory.net 도메인을 쓰기 전, my.netian.com/~fstory 에 있던 홈페이지. 첫 화면에 \"1999.3.17부터 방문자\"와 \"100% 메모장 노가다\" 라고 적혀 있다. L1 클래식 계보와 같은 title1~4.gif 이미지맵 메뉴를 쓴다."
    },
    {
        "id": "chollian-guestbook",
        "label": "천리안 방명록",
        "period": "2001 ~ 2002",
        "snapshot": "20021128181318",
        "entry": "chollian/cgi/pury/purybbs.html",
        "summary": "cgi.chollian.net/~foreststory 에 있던 PURY BBS 방명록. 목록 화면에 글 본문이 그대로 실리는 형식이라 오간 글과 답글이 남아 있다. 캡처마다 다른 쪽이 잡혀서 한 캡처만으로는 일부만 보이므로, 모든 캡처의 글을 번호로 합쳐 한 페이지로 다시 세웠다."
    }
];

export const FSTORY_EDITION_IDS = FSTORY_EDITIONS.map((edition) => edition.id);

export const editionOf = (id: string) => FSTORY_EDITIONS.find((edition) => edition.id === id);
